name: test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install poetry
        shell: bash
        run: curl -sSL https://install.python-poetry.org | python3 -

      - uses: actions/checkout@v2

      - name: Cache poetry
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-pypoetry-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pypoetry-

      - name: Cache pre-commit
        uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-

      - name: Install dependencies
        run: poetry install

      - name: Lint
        uses: pre-commit/action@v2.0.3

      - name: Test
        run: PYTHONPATH=./app poetry run pytest ./tests/
